### ISSUE TITLE
Cannot build on real iphone

### ISSUE THREAD

**Issue by ndhuy96** [NAXAM/accountkit-ios-binding#3]
Account kit is only working if I test on iphone simulator. When I build on real iphone, i meet an issue. Can you tell me what does this error mean?
'Native linking failed for arm64/libNaxam.AccountKit.iOS.dll.dylib'

**Comment by tuyen-vuduc** [comment]
Plz try again in 1 hour.

**Comment by ndhuy96** [comment]
I upgrade version 4.35 but it still has the same error :(  Btw I use VS 7.4.3 (build 10)
This error appear after I upgrade Visual Studio 2017.

**Comment by tuyen-vuduc** [comment]
1. Plz delete your bin/obj folders
2. Plz disable linker when you debug on iPhone

**Comment by ndhuy96** [comment]
I tried but it didn't work at all 
Here is my project: https://github.com/ndhuy96/Projects/tree/master/TestApp

**Comment by tuyen-vuduc** [comment]
Hey @ndhuy96,

Plz copy your error here so I could investigate. It's more helpful and friendly when reporting an issue of any open source library.

I tried to run your sample application, but it contains a lot of things, it doesn't show up the integration with AK at front.

In the meanwhile, here is the sample code that I created to verify the package is ok or not.

Check it out.
[AccountKitTrial.zip](https://github.com/NAXAM/accountkit-ios-binding/files/2254269/AccountKitTrial.zip)

Cheers.

**Comment by ndhuy96** [comment]
I runned your sample and it worked successfully. 
Howerer, I want to use it in my Xamarin Shared Projects.
Here is my project: https://github.com/ndhuy96/Projects/tree/master/AccountKitSample/AccountKitSample

By the way, Naxam Account Kit is really helpful to me!
<img width="1680" alt="screen shot 2018-08-03 at 8 47 59 am" src="https://user-images.githubusercontent.com/26228562/43620029-e68bb8a4-96fa-11e8-9773-bad9b8a71666.png">

**Comment by tuyen-vuduc** [comment]
Hey,

I noted you previously
```
Plz disable linker when you debug on iPhone
```

Because you could run the sample code successfully, I am closing this issue.

Cheers
